version: "3.7"

services:
  database:
    container_name: database
    image: postgres:14.2-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      # wait interval seconds before running check
      # and wait same amount after check completes
      interval: 1s
      # if check takes longer than timeout, check
      # is considered as fail
      timeout: 2s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=projectsmoothies
      - POSTGRES_DB=postgres

  flask:
    container_name: flask
    image: bila9630/dbflask
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ./Application
    # restart: always
    ports:
      - 5001:5001
    networks:
      - app-network

  frontend:
    container_name: frontend
    image: bila9630/frontend
    build:
      context: ./Frontend
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
