version: "3.7"

services:
  flask:
    image: bila9630/dbflask
    build:
      context: ./Application
    ports:
      - 5001:5001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
